name: "Artwork submission"
description: "Submit SymbOS/MSX artwork (PNG/JPEG + SGX required)"
title: "[SUBMISSION] "
labels: ["submission"]
body:
  - type: input
    id: title
    attributes:
      label: Artwork title
      placeholder: "Kenshiro Sunset"
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: Author / Nickname
      placeholder: "zezinho2345"
    validations:
      required: true

  - type: dropdown
    id: format
    attributes:
      label: Image format
      options:
        - PNG + SGX
        - JPEG + SGX
    validations:
      required: true

  - type: textarea
    id: links
    attributes:
      label: Files (attach or link)
      description: |
        Attach both files here (drag & drop), OR provide download links.
        REQUIRED: image + sgx with the same base filename.
      placeholder: |
        Attach: myart.png and myart.sgx
        or links:
        - https://...
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Short description
      placeholder: "A SymbOS 16-color wallpaper inspired by..."
    validations:
      required: false

  - type: checkboxes
    id: rules
    attributes:
      label: Submission rules
      options:
        - label: "I confirm I am the author or have rights to submit this artwork."
          required: true
        - label: "I confirm this submission includes PNG/JPEG + SGX with the same base filename."
          required: true
        - label: "I confirm this artwork is intended for SymbOS/MSX use."
          required: true
